version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment: 
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes: 
  postgres-data:
